name: aws resource creation
on: 
  push:
    branches:
    - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: check-out repo code
      uses: actions/checkout@v4

    - name: set up terraform on runner
      uses: hashicorp/setup-terraform@v3

    - name: initialization terraform
      run: terraform init

    - name: configuring aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: us-east-1

    - name: planning the terraform module
      run: terraform plan